server:
  port: 8081

#Имя приложения для Eureka.
spring:
  application:
    name: user-service

  #Настройки базы данных.
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_test
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  #Настройки Kafka Producer.
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      properties:
        max.block.ms: 5000
        request.timeout.ms: 30000
        delivery.timeout.ms: 120000
    admin:
      properties:
        auto.create.topics.enable: false

  #Разрешить переопределение бинов.
  main:
    allow-bean-definition-overriding: true

#Swagger/OpenAPI
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  show-actuator: false
  model-converters:
    hal-converter:
      enabled: false
  default-produces-media-type: application/json
  use-fqn: false

#Logging
logging:
  level:
    org.klimtsov: DEBUG
    org.springframework.web: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: INFO

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always